"""Generate the boundary stub TU + export list for a lifted module.

Every symbol the lifted code references but does not define gets a stub:
  * `sub_XXXXXXXX` for callees outside the lifted set
  * `recomp_other_*` for SLEIGH CALLOTHER intrinsics
  * `imp_<stem>__<symbol>` for resolved IAT slots

THESE STUBS ABORT.  They exist so a module missing its host layer fails
loudly and names the symbol, not so it runs.

An earlier version returned `s->EIP = MEMR32(s->ESP); s->ESP += 4;` --
a cdecl return -- for every import.  That is correct for the 263 cdecl
imports and WRONG for the 315 stdcall ones, which must also pop their
arguments.  A stdcall import stubbed as cdecl leaves the guest stack
desynchronised by the argument bytes and every subsequent frame is
garbage: the failure surfaces arbitrarily far from its cause and points
nowhere.  Silence is the worst possible behaviour here, so the stub
aborts with the symbol name instead of guessing a convention.

The real implementations live in the host layer (`scripts/recomp/host/`),
which owns the stdcall purge because it is the layer that knows each
symbol's argument bytes and has cross-checked them against the curated
signatures.  Link against it; these stubs are only a link-completeness
backstop.
"""

import argparse
import glob
import json
import os
import re


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", required=True)
    ap.add_argument("--no-import-stubs", action="store_true",
                    help="omit imp_<stem>__<symbol> placeholders entirely. "
                         "REQUIRED when linking the host layer: it emits its "
                         "own weak fallback for all 622 imports, and two weak "
                         "definitions of one symbol let the linker pick either "
                         "-- silently. The host's version names the DLL, the "
                         "symbol, its stdcall argument bytes and its call-site "
                         "count, so it must be the one that survives.")
    args = ap.parse_args()
    d = args.dir

    decls = open(os.path.join(d, "lifted_decls.h"), encoding="utf8").read()
    missing = [l.strip() for l in open(os.path.join(d, "missing.txt"))
               if l.strip()]
    others = re.findall(r"uint32_t recomp_other_(\w+)\(([^)]*)\);", decls)
    others_wide = re.findall(r"void recomp_otherw_(\w+)\(([^)]*)\);", decls)
    shims = re.findall(r"void (imp_\w+)\(CpuState", decls)

    names = set()
    for f in sorted(glob.glob(os.path.join(d, "lifted*.c"))):
        with open(f, encoding="utf8") as fh:
            names.update(re.findall(r"^void (sub_[0-9a-f]{8})\(CpuState",
                                    fh.read(), re.M))

    with open(os.path.join(d, "stubs.c"), "w") as fh:
        fh.write('/* GENERATED by mkstubs.py -- loud placeholders only.\n'
                 ' * Every symbol here aborts and names itself.  Link the\n'
                 ' * host layer (scripts/recomp/host/) to replace them; a\n'
                 ' * module that runs on these stubs is a module whose guest\n'
                 ' * stack would silently desynchronise. */\n')
        fh.write('#include "lifted_decls.h"\n')
        fh.write('#include <stdio.h>\n#include <stdlib.h>\n\n')
        fh.write('__attribute__((noreturn, noinline))\n'
                 'static void recomp_missing(const char *kind, const char *sym) {\n'
                 '  fprintf(stderr, "recomp: no host implementation for %s %s\\n"\n'
                 '                  "  (link scripts/recomp/host/ -- these stubs "\n'
                 '                  "abort rather than guess a calling convention)\\n",\n'
                 '          kind, sym);\n'
                 '  abort();\n'
                 '}\n\n')
        for va in missing:
            n = int(va, 16)
            fh.write('__attribute__((weak)) void sub_%08x(CpuState *restrict s)'
                     ' { (void)s; recomp_missing("callee", "sub_%08x"); }\n'
                     % (n, n))
        for n, params in others:
            ps = [x.strip() for x in params.split(",")]
            sig = ", ".join(p + " a%d" % i if p == "uint32_t" else p
                            for i, p in enumerate(ps))
            fh.write('__attribute__((weak)) uint32_t recomp_other_%s(%s)'
                     ' { (void)s; recomp_missing("intrinsic", "%s"); }\n'
                     % (n, sig, n))
        for n, params in others_wide:
            # wide decls already name their parameters
            fh.write('__attribute__((weak)) void recomp_otherw_%s(%s)'
                     ' { (void)s; recomp_missing("intrinsic", "%s"); }\n'
                     % (n, params, n))
        if not args.no_import_stubs:
            for n in shims:
                # NB: no cdecl epilogue here on purpose -- 315 of the 587
                # imports are stdcall and must pop their arguments. The host
                # layer owns the per-symbol argument bytes; guessing here
                # desynchronises the guest stack.
                fh.write('__attribute__((weak)) void %s(CpuState *restrict s)'
                         ' { (void)s; recomp_missing("import", "%s"); }\n'
                         % (n, n))

    with open(os.path.join(d, "exports.json"), "w") as fh:
        json.dump(sorted("_" + n for n in names), fh)

    print(json.dumps(dict(missing_callees=len(missing),
                          callother_intrinsics=len(others),
                          import_shims=0 if args.no_import_stubs else len(shims),
                          import_stubs_omitted=len(shims) if args.no_import_stubs else 0,
                          exports=len(names)), indent=1))


if __name__ == "__main__":
    main()
